fastlane_require "dotenv"

before_all do
  UI.important "Loading secret environment variables"
  Dotenv.load ".env.secret"
end

desc "Create app on developer portal and App Store Connect if needed"
lane :create_app do
  produce
end

platform :ios do
  before_all do
    UI.important "Loading iOS environment variables"
    Dotenv.load ".env.ios"
  end

  desc "Bump version"
  lane :bump do
    increment_version_number(version_number: UI.input("Version number:"))
  end

  desc "Sync signing"
  lane :signing do
    match

    mapping = Actions.lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]
    update_code_signing_settings(
      profile_name: mapping[ENV['MATCH_APP_IDENTIFIER']]
    )
  end

  desc "Build binary"
  lane :build do
    signing
    build_ios_app
  end

  desc "Release binary"
  lane :release do
    ensure_git_status_clean
    ensure_git_branch

    increment_build_number(build_number: Time.now.to_i)

    build
    deliver

    reset_git_repo

    add_git_tag(tag: get_version_number)
    push_git_tags

    set_github_release(
      name: last_git_tag,
      tag_name: last_git_tag,
      description: ""
    )
  end
end

platform :mac do
  before_all do
    UI.important "Loading macOS environment variables"
    Dotenv.load ".env.mac"
  end

  desc "Bump version"
  lane :bump do
    increment_version_number(version_number: UI.input("Version number:"))
  end

  desc "Sync signing"
  lane :signing do
    match

    mapping = Actions.lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]
    update_code_signing_settings(
      profile_name: mapping[ENV['MATCH_APP_IDENTIFIER']]
    )
  end

  desc "Build binary"
  lane :build do
    signing
    build_mac_app
  end

  desc "Release binary"
  lane :release do
    ensure_git_status_clean
    ensure_git_branch

    increment_build_number(build_number: Time.now.to_i)

    build
    deliver

    reset_git_repo
  end
end
